version: 2
jobs:
  tests:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Check coding standard by ESLint
          command: npm run lint

  deploy-dev:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.10

    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run:
          name: integration test
          command: npm run test:integration

  deploy-prod:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.10

    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run:
          name: integration test
          command: npm run test:integration

workflows:
  version: 2
  build-deploy:
    jobs:
      - tests:
          filters:
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
      - deploy-dev:
          requires:
            - tests
          filters:
            tags:
              only: /.*/
            branches:
              only: master
      - deploy-prod:
          requires:
            - tests
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/